.TH "ncelinks" 3 "19 May 2013" "Version 0.7.2" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ncelinks \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBncelinks\fP * \fBnext\fP"
.br
.RI "\fInext in list \fP"
.ti -1c
.RI "struct \fBncelinks\fP * \fBprev\fP"
.br
.RI "\fIprevious in list \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file ccnd_private.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBncelinks\fP* \fBncelinks::next\fP"
.PP
next in list 
.PP
Definition at line 77 of file ccnd_private.h.
.PP
Referenced by ccnd_create(), finalize_nonce(), and nonce_ok().
.SS "struct \fBncelinks\fP* \fBncelinks::prev\fP"
.PP
previous in list 
.PP
Definition at line 78 of file ccnd_private.h.
.PP
Referenced by ccnd_create(), finalize_nonce(), and nonce_ok().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
