Content-Centric Networking in C: sync/SyncTest.c File Reference
SyncTest.c File Reference
Part of CCNx Sync.
Defines
#define MAX_READ_LEN 1000000
#define DEFAULT_CMD_TIMEOUT 6000
Functions
static int noteErr (const char *fmt,...)
static int parseAndAccumName (char *s, struct SyncNameAccum *na)
static struct SyncNameAccum * readAndAccumNames (FILE *input, int rem)
static void printTreeInner (struct SyncTreeWorkerHead *head, struct ccn_charbuf *tmpB, struct ccn_charbuf *tmpD, FILE *f)
static void printTree (struct SyncTreeWorkerHead *head, FILE *f)
static void putMark (FILE *f)
static struct SyncNodeComposite * testGenComposite (struct SyncBaseStruct *base, int nRefs)
static int testEncodeDecode (struct SyncTestParms *parms)
static int testReader (struct SyncTestParms *parms)
static int testReadBuilder (struct SyncTestParms *parms)
static struct SyncRootStruct * genTestRootRouting (struct SyncTestParms *parms)
static struct SyncRootStruct * genTestRootRepos (struct SyncTestParms *parms)
static struct SyncRootStruct * testRootCoding (struct SyncTestParms *parms, struct SyncRootStruct *root)
static int testRootLookup (struct SyncTestParms *parms, struct SyncRootStruct *root, char *goodName, char *badName)
static int testRootBasic (struct SyncTestParms *parms)
static int localStore (struct SyncTestParms *parms, struct ccn *ccn, struct ccn_charbuf *nm, struct ccn_charbuf *cb)
static int sendSlice (struct SyncTestParms *parms, char *topo, char *prefix, int count, char **clauses)
static int64_t segFromInfo (struct ccn_upcall_info *info)
static enum ccn_upcall_res storeHandler (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static void formatStats (struct SyncTestParms *parms)
static int getFile (struct SyncTestParms *parms, char *src, char *dst)
static int putFile (struct SyncTestParms *parms, char *src, char *dst)
int appendComponents (struct ccn_charbuf *dst, const struct ccn_charbuf *src, int start, int len)
static int putFileList (struct SyncTestParms *parms, char *listName)
static int existingRootOp (struct SyncTestParms *parms, char *topo, char *prefix, int delete)
static void my_r_sync_msg (struct sync_plumbing *sd, const char *fmt,...)
static void SyncFreeBase (struct SyncBaseStruct *base)
int ccnr_msg_level_from_string (const char *s)
int main (int argc, char **argv)
Variables
struct sync_plumbing_client_methods client_methods
Detailed Description
Part of CCNx Sync.
Definition in file SyncTest.c.
Define Documentation
#define DEFAULT_CMD_TIMEOUT 6000
Definition at line 50 of file SyncTest.c.
Referenced by existingRootOp(), localStore(), putFile(), and putFileList().
#define MAX_READ_LEN 1000000
Definition at line 49 of file SyncTest.c.
Referenced by putFileList(), testReadBuilder(), and testReader().
Function Documentation
int appendComponents (struct ccn_charbuf * dst, const struct ccn_charbuf * src, int start, int len)
Definition at line 1307 of file SyncTest.c.
Referenced by putFileList().
int ccnr_msg_level_from_string (const char * s)
Definition at line 1516 of file SyncTest.c.
static int existingRootOp (struct SyncTestParms * parms, char * topo, char * prefix, int delete) [static]
Definition at line 1416 of file SyncTest.c.
Referenced by main().
static void formatStats (struct SyncTestParms * parms) [static]
Definition at line 963 of file SyncTest.c.
Referenced by getFile(), and putFile().
static struct SyncRootStruct* genTestRootRepos (struct SyncTestParms * parms) [static, read]
Definition at line 525 of file SyncTest.c.
Referenced by testRootBasic().
static struct SyncRootStruct* genTestRootRouting (struct SyncTestParms * parms) [static, read]
Definition at line 505 of file SyncTest.c.
Referenced by testRootBasic().
static int getFile (struct SyncTestParms * parms, char * src, char * dst) [static]
Definition at line 1018 of file SyncTest.c.
Referenced by main().
static int localStore (struct SyncTestParms * parms, struct ccn * ccn, struct ccn_charbuf * nm, struct ccn_charbuf * cb) [static]
Definition at line 665 of file SyncTest.c.
Referenced by existingRootOp(), and sendSlice().
int main (int argc, char ** argv)
Definition at line 1546 of file SyncTest.c.
static void my_r_sync_msg (struct sync_plumbing * sd, const char * fmt, ...) [static]
Definition at line 1489 of file SyncTest.c.
static int noteErr (const char * fmt, ...) [static]
Definition at line 90 of file SyncTest.c.
Referenced by existingRootOp(), main(), putFile(), putFileList(), sendSlice(), storeHandler(), testReadBuilder(), testReader(), testRootBasic(), testRootCoding(), and testRootLookup().
static int parseAndAccumName (char * s, struct SyncNameAccum * na) [static]
Definition at line 111 of file SyncTest.c.
Referenced by readAndAccumNames().
static void printTree (struct SyncTreeWorkerHead * head, FILE * f) [static]
Definition at line 249 of file SyncTest.c.
Referenced by testReadBuilder().
static void printTreeInner (struct SyncTreeWorkerHead * head, struct ccn_charbuf * tmpB, struct ccn_charbuf * tmpD, FILE * f) [static]
Definition at line 201 of file SyncTest.c.
Referenced by printTree().
static int putFile (struct SyncTestParms * parms, char * src, char * dst) [static]
Definition at line 1171 of file SyncTest.c.
Referenced by main().
static int putFileList (struct SyncTestParms * parms, char * listName) [static]
Definition at line 1344 of file SyncTest.c.
Referenced by main().
static void putMark (FILE * f) [static]
Definition at line 257 of file SyncTest.c.
Referenced by existingRootOp(), formatStats(), putFile(), putFileList(), sendSlice(), and storeHandler().
static struct SyncNameAccum* readAndAccumNames (FILE * input, int rem) [static, read]
Definition at line 150 of file SyncTest.c.
Referenced by putFileList(), testReadBuilder(), and testReader().
static int64_t segFromInfo (struct ccn_upcall_info * info) [static]
Definition at line 807 of file SyncTest.c.
Referenced by storeHandler().
static int sendSlice (struct SyncTestParms * parms, char * topo, char * prefix, int count, char ** clauses) [static]
Definition at line 708 of file SyncTest.c.
Referenced by main().
static enum ccn_upcall_res storeHandler (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 846 of file SyncTest.c.
Referenced by putFile().
static void SyncFreeBase (struct SyncBaseStruct * base) [static]
Definition at line 1507 of file SyncTest.c.
Referenced by main().
static int testEncodeDecode (struct SyncTestParms * parms) [static]
Definition at line 292 of file SyncTest.c.
Referenced by main().
static struct SyncNodeComposite* testGenComposite (struct SyncBaseStruct * base, int nRefs) [static, read]
Definition at line 271 of file SyncTest.c.
Referenced by testEncodeDecode().
static int testReadBuilder (struct SyncTestParms * parms) [static]
Definition at line 388 of file SyncTest.c.
Referenced by main().
static int testReader (struct SyncTestParms * parms) [static]
Definition at line 324 of file SyncTest.c.
Referenced by main().
static int testRootBasic (struct SyncTestParms * parms) [static]
Definition at line 621 of file SyncTest.c.
Referenced by main().
static struct SyncRootStruct* testRootCoding (struct SyncTestParms * parms, struct SyncRootStruct * root) [static, read]
Definition at line 552 of file SyncTest.c.
Referenced by testRootBasic().
static int testRootLookup (struct SyncTestParms * parms, struct SyncRootStruct * root, char * goodName, char * badName) [static]
Definition at line 599 of file SyncTest.c.
Referenced by testRootBasic().
Variable Documentation
struct sync_plumbing_client_methods client_methods
Initial value:
 {
    &my_r_sync_msg,
    NULL,
    NULL,
    NULL,
    NULL
}
Definition at line 1498 of file SyncTest.c.