Content-Centric Networking in C: include/ccn/hashtb.h File Reference
hashtb.h File Reference
Hash table.
Data Structures
struct hashtb_param
struct hashtb_enumerator
Defines
#define HT_OLD_ENTRY 0
#define HT_NEW_ENTRY 1
Typedefs
typedef void(* hashtb_finalize_proc)(struct hashtb_enumerator *)
Functions
size_t hashtb_hash (const unsigned char *key, size_t key_size)
struct hashtb * hashtb_create (size_t item_size, const struct hashtb_param *param)
void * hashtb_get_param (struct hashtb *ht, struct hashtb_param *param)
void hashtb_destroy (struct hashtb **ht)
int hashtb_n (struct hashtb *ht)
void * hashtb_lookup (struct hashtb *ht, const void *key, size_t keysize)
struct hashtb_enumerator * hashtb_start (struct hashtb *, struct hashtb_enumerator *)
void hashtb_end (struct hashtb_enumerator *)
void hashtb_next (struct hashtb_enumerator *)
int hashtb_seek (struct hashtb_enumerator *hte, const void *key, size_t keysize, size_t extsize)
void hashtb_delete (struct hashtb_enumerator *)
void hashtb_rehash (struct hashtb *ht, unsigned n_buckets)
Detailed Description
Hash table.
Part of the CCNx C Library.
Copyright (C) 2008, 2009, 2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file hashtb.h.
Define Documentation
#define HT_NEW_ENTRY 1
Definition at line 118 of file hashtb.h.
Referenced by ccn_btree_getnode(), ccn_cache_key(), ccn_express_interest(), ccn_load_private_key(), ccn_locate_key(), ccnd_set_face_guid(), finalize_content(), hashtb_seek(), nameprefix_seek(), nonce_ok(), process_incoming_content(), propagate_interest(), r_proto_begin_enumeration(), r_store_forget_content(), and record_connection().
#define HT_OLD_ENTRY 0
Definition at line 117 of file hashtb.h.
Referenced by ccn_get_public_key(), ccn_load_private_key(), ccn_sign_content(), ccnd_reg_prefix(), consume_interest(), hashtb_seek(), main(), nonce_ok(), process_incoming_content(), r_proto_begin_enumeration(), r_proto_continue_enumeration(), remove_content(), and shutdown_client_fd().
Typedef Documentation
typedef void(* hashtb_finalize_proc)(struct hashtb_enumerator *)
Definition at line 29 of file hashtb.h.
Function Documentation
struct hashtb* hashtb_create (size_t item_size, const struct hashtb_param * param) [read]
Definition at line 62 of file hashtb.c.
Referenced by ccn_btree_create(), ccn_create(), ccn_express_interest(), ccn_set_interest_filter_with_flags(), ccnd_create(), main(), r_init_create(), and r_store_init().
void hashtb_delete (struct hashtb_enumerator *)
Definition at line 261 of file hashtb.c.
Referenced by ccn_cache_key(), ccn_clean_all_interests(), ccn_get_public_key(), ccn_set_interest_filter_with_flags(), ccn_sign_content(), ccnd_destroy_face(), ccnd_forget_face_guid(), ccnd_shutdown_listeners(), check_dgram_faces(), check_nameprefix_entries(), clean_guest(), consume_interest(), finalize_content(), get_dgram_source(), hashtb_destroy(), main(), nonce_ok(), process_incoming_content(), r_store_forget_content(), r_store_index_cleaner(), reap_enumerations(), record_connection(), remove_content(), and shutdown_client_fd().
void hashtb_destroy (struct hashtb ** ht)
Definition at line 90 of file hashtb.c.
Referenced by ccn_btree_destroy(), ccn_destroy(), ccnd_destroy(), main(), and r_init_destroy().
void hashtb_end (struct hashtb_enumerator *)
Definition at line 179 of file hashtb.c.
Referenced by age_forwarding(), ccn_btree_getnode(), ccn_cache_key(), ccn_clean_all_interests(), ccn_destroy(), ccn_disconnect(), ccn_express_interest(), ccn_get_public_key(), ccn_load_private_key(), ccn_locate_key(), ccn_notify_ccndid_changed(), ccn_process_scheduled_operations(), ccn_set_interest_filter_with_flags(), ccn_sign_content(), ccnd_collect_stats(), ccnd_destroy_face(), ccnd_forget_face_guid(), ccnd_getboundsocket(), ccnd_reg_prefix(), ccnd_req_guest(), ccnd_set_face_guid(), ccnd_shutdown_listeners(), ccnr_collect_stats(), check_dgram_faces(), check_nameprefix_entries(), clean_guest(), cleanout_stragglers(), collect_forwarding_html(), collect_forwarding_xml(), consume_interest(), Dump(), finalize_content(), get_dgram_source(), hashtb_destroy(), main(), make_connection(), nonce_ok(), prepare_poll_fds(), process_incoming_content(), process_incoming_interest(), propagate_interest(), r_proto_begin_enumeration(), r_proto_continue_enumeration(), r_proto_dump_enums(), r_store_enroll_content(), r_store_forget_content(), r_store_index_cleaner(), r_store_set_accession_from_offset(), reap_enumerations(), record_connection(), remove_content(), setup_multicast(), shutdown_client_fd(), and update_npe_children().
void* hashtb_get_param (struct hashtb * ht, struct hashtb_param * param)
Definition at line 82 of file hashtb.c.
Referenced by finalize_accession(), finalize_content(), finalize_face(), finalize_interest(), finalize_nameprefix(), finalize_node(), finally(), and r_fwd_finalize_nameprefix().
size_t hashtb_hash (const unsigned char * key, size_t key_size)
Definition at line 52 of file hashtb.c.
Referenced by ccnd_debug_ccnb(), hashtb_lookup(), and hashtb_seek().
void* hashtb_lookup (struct hashtb * ht, const void * key, size_t keysize)
Definition at line 115 of file hashtb.c.
Referenced by ccn_btree_rnode(), ccn_check_pub_arrival(), ccn_dispatch_message(), ccn_locate_key(), ccnd_debug_ccnb(), ccnd_faceid_from_guid(), ccnd_req_unreg(), content_from_accession(), do_deferred_write(), faceid_from_fd(), main(), match_interests(), process_incoming_interest(), process_input(), r_match_match_interests(), r_store_content_from_accession(), and r_store_look().
int hashtb_n (struct hashtb * ht)
Definition at line 109 of file hashtb.c.
Referenced by ccn_btree_check(), clean_daemon(), cleanout_stragglers(), collect_stats_html(), collect_stats_xml(), Dump(), expire_content(), prepare_poll_fds(), process_incoming_content(), r_store_index_cleaner(), reap_enumerations(), and test_btree_init().
void hashtb_next (struct hashtb_enumerator *)
Definition at line 203 of file hashtb.c.
Referenced by age_forwarding(), ccn_clean_all_interests(), ccn_destroy(), ccn_disconnect(), ccn_notify_ccndid_changed(), ccn_process_scheduled_operations(), ccnd_collect_stats(), ccnd_getboundsocket(), ccnd_shutdown_listeners(), ccnr_collect_stats(), check_dgram_faces(), check_nameprefix_entries(), collect_forwarding_html(), collect_forwarding_xml(), Dump(), make_connection(), prepare_poll_fds(), r_proto_dump_enums(), r_store_index_cleaner(), reap_enumerations(), setup_multicast(), and update_npe_children().
void hashtb_rehash (struct hashtb * ht, unsigned n_buckets)
Definition at line 286 of file hashtb.c.
Referenced by hashtb_seek().
int hashtb_seek (struct hashtb_enumerator * hte, const void * key, size_t keysize, size_t extsize)
Definition at line 217 of file hashtb.c.
Referenced by ccn_btree_getnode(), ccn_cache_key(), ccn_express_interest(), ccn_get_public_key(), ccn_load_private_key(), ccn_locate_key(), ccn_set_interest_filter_with_flags(), ccn_sign_content(), ccnd_destroy_face(), ccnd_forget_face_guid(), ccnd_req_guest(), ccnd_set_face_guid(), clean_guest(), cleanout_stragglers(), consume_interest(), finalize_content(), get_dgram_source(), main(), nameprefix_seek(), nonce_ok(), process_incoming_content(), propagate_interest(), r_proto_begin_enumeration(), r_proto_continue_enumeration(), r_store_enroll_content(), r_store_forget_content(), r_store_set_accession_from_offset(), record_connection(), remove_content(), and shutdown_client_fd().
struct hashtb_enumerator* hashtb_start (struct hashtb * , struct hashtb_enumerator *) [read]
Definition at line 166 of file hashtb.c.
Referenced by age_forwarding(), ccn_btree_getnode(), ccn_cache_key(), ccn_clean_all_interests(), ccn_destroy(), ccn_disconnect(), ccn_express_interest(), ccn_get_public_key(), ccn_load_private_key(), ccn_locate_key(), ccn_notify_ccndid_changed(), ccn_process_scheduled_operations(), ccn_set_interest_filter_with_flags(), ccn_sign_content(), ccnd_collect_stats(), ccnd_destroy_face(), ccnd_forget_face_guid(), ccnd_getboundsocket(), ccnd_reg_prefix(), ccnd_req_guest(), ccnd_set_face_guid(), ccnd_shutdown_listeners(), ccnr_collect_stats(), check_dgram_faces(), check_nameprefix_entries(), clean_guest(), cleanout_stragglers(), collect_forwarding_html(), collect_forwarding_xml(), consume_interest(), Dump(), finalize_content(), get_dgram_source(), hashtb_destroy(), main(), make_connection(), nonce_ok(), prepare_poll_fds(), process_incoming_content(), process_incoming_interest(), propagate_interest(), r_proto_begin_enumeration(), r_proto_continue_enumeration(), r_proto_dump_enums(), r_store_enroll_content(), r_store_forget_content(), r_store_index_cleaner(), r_store_set_accession_from_offset(), reap_enumerations(), record_connection(), remove_content(), setup_multicast(), shutdown_client_fd(), and update_npe_children().