Content-Centric Networking in C: include/ccn/uri.h File Reference
uri.h File Reference
ccn-scheme uri conversions.
Defines
#define CCN_URI_INCLUDESCHEME 1
#define CCN_URI_MIXEDESCAPE 2
#define CCN_URI_PERCENTESCAPE 4
#define CCN_URI_ESCAPE_MASK (CCN_URI_MIXEDESCAPE|CCN_URI_PERCENTESCAPE)
#define CCN_URI_DEFAULT_ESCAPE CCN_URI_PERCENTESCAPE
Functions
void ccn_uri_append_percentescaped (struct ccn_charbuf *c, const unsigned char *data, size_t size)
This appends to c a percent-escaped representation of the component passed in.
void ccn_uri_append_mixedescaped (struct ccn_charbuf *c, const unsigned char *data, size_t size)
int ccn_uri_append (struct ccn_charbuf *c, const unsigned char *ccnb, size_t size, int flags)
This appends to c a URI representation of the ccnb-encoded Name element passed in.
int ccn_name_from_uri (struct ccn_charbuf *c, const char *uri)
Convert a ccnx-scheme URI to a ccnb-encoded Name.
Detailed Description
ccn-scheme uri conversions.
Part of the CCNx C Library.
Copyright (C) 2008, 2009, 2010, 2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file uri.h.
Define Documentation
#define CCN_URI_DEFAULT_ESCAPE CCN_URI_PERCENTESCAPE
Definition at line 44 of file uri.h.
Referenced by ccn_uri_append().
#define CCN_URI_ESCAPE_MASK (CCN_URI_MIXEDESCAPE|CCN_URI_PERCENTESCAPE)
Definition at line 42 of file uri.h.
Referenced by ccn_uri_append().
#define CCN_URI_INCLUDESCHEME 1
Definition at line 38 of file uri.h.
Referenced by ccn_uri_append(), and main().
#define CCN_URI_MIXEDESCAPE 2
Definition at line 39 of file uri.h.
Referenced by ccn_uri_append(), and main().
#define CCN_URI_PERCENTESCAPE 4
Definition at line 40 of file uri.h.
Referenced by ccn_uri_append(), and main().
Function Documentation
int ccn_name_from_uri (struct ccn_charbuf * c, const char * uri)
Convert a ccnx-scheme URI to a ccnb-encoded Name.
The converted result is placed in c. On input, c may contain a base name, in which case relative URIs are allowed. Otherwise c should start out empty, and the URI must be absolute.
Returns:
-1 if an error is found, otherwise returns the number of characters that were processed.
Definition at line 321 of file ccn_uri.c.
Referenced by add_uri_exclusion(), append_adjacency_uri(), ccn_guest_prefix(), ccn_initiate_ccndid_fetch(), ccn_initiate_prefix_reg(), ccnd_adjacency_offer_or_commit_req(), ccnd_init_face_guid_cob(), ccnd_init_service_ccnb(), ccnd_parse_uri_list(), ccnd_reg_ccnx_ccndid(), ccnd_reg_uri(), ccnd_req_guest(), ccnd_start_notice(), ccnd_uri_listen(), ccndc_daemonize(), ccndc_get_ccnd_id(), ccnr_init_policy_cob(), ccnr_init_policy_link_cob(), ccnr_init_service_ccnb(), ccnr_uri_listen(), ccns_slice_name(), existingRootOp(), genTestRootRepos(), genTestRootRouting(), getFile(), initialize(), load_policy(), localStore(), main(), NewElem(), parse_ccn_forwarding_entry(), parseAndAccumName(), putFile(), r_proto_append_repo_info(), r_proto_uri_listen(), send_adjacency_solicit(), sendSlice(), stuff_link_check(), SyncNewBase(), test_flatname(), testReadBuilder(), testRootLookup(), and write_slice().
int ccn_uri_append (struct ccn_charbuf * c, const unsigned char * ccnb, size_t size, int flags)
This appends to c a URI representation of the ccnb-encoded Name element passed in.
For convenience, it will also look inside of a ContentObject or Interest object to find the Name. Components that consist solely of zero or more dots are converted by adding 3 more dots so there are no ambiguities with . or .. or whether a component is empty or absent. Will prepend "ccnx:" if flags & CCN_URI_INCLUDESCHEME is not 0 Will escape with "%" and "=" if flags & CCN_URI_MIXEDESCAPES is not 0
Definition at line 141 of file ccn_uri.c.
Referenced by append_adjacency_uri(), ccn_uri_append_flatname(), ccnd_debug_ccnb(), ccnd_reg_ccnx_ccndid(), ccnd_req_guest(), ccnd_uri_listen(), ccnr_debug_ccnb(), ccnr_uri_listen(), collect_forwarding_html(), collect_forwarding_xml(), debug_logger(), incoming_content(), main(), printTreeInner(), process_data(), storeHandler(), sync_cb(), SyncRootLookupName(), SyncUriForName(), test_flatname(), and testReader().
void ccn_uri_append_mixedescaped (struct ccn_charbuf * c, const unsigned char * data, size_t size)
Definition at line 86 of file ccn_uri.c.
Referenced by ccn_uri_append().
void ccn_uri_append_percentescaped (struct ccn_charbuf * c, const unsigned char * data, size_t size)
This appends to c a percent-escaped representation of the component passed in.
Only generic URI unreserved characters are not escaped. Components that consist solely of zero or more dots are converted by adding 3 more dots so there are no ambiguities with . or .. or whether a component is empty or absent. (cf. ccn_uri_append)
Definition at line 62 of file ccn_uri.c.
Referenced by append_interest_details(), ccn_uri_append(), ccnd_append_excludes(), and ccndc_srv().